### ISSUE TITLE
Should time delays and intervals be an int or float?

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#10]
Current opinions from other threads:

@bwoebi https://github.com/async-interop/event-loop/issues/6#issuecomment-186619234

> @AndrewCarterUK why are you proposing floats for times? The precision of the reactors/loops is one millisecond. (Some do allow for more, but e.g. for uv it's at most one millisecond. And we should be able to get same results for each backend.) At least that's the reason why Amp choose to use milliseconds as base unit and should be retained here.

@trowski 

> @bwoebi Perhaps someday there can be greater precision than 1 ms. Using a float allows for that.

@bwoebi

> @trowski If there will ever be, it will be a BC break (significant enough for a major I mean) anyway as currently we should guarantee that all the backends use the same granularity for time management and that granularity would be changed too.

**Comment by kelunik** [comment]
As already mentioned, I'm for `int`. If we choose `float`, I'm still for milliseconds as unit of time.

**Comment by trowski** [comment]
The thing I like about `float` is that `1.5` will always be 1.5 seconds. With an `int`, `1500` means 1.5 seconds now, but if a future version allows 0.1 ms accuracy, then perhaps `15000` would be needed for 1.5 seconds, causing a BC break.

**Comment by bwoebi** [comment]
It will also cause a BC break if we pass 0.0015 in and in future behavior changes because it actually doesn't get rounded down. Causing a BC break too.

It's like in physics … if you use natural units, most things are expressible as simple fractions or integers, if you use "weird" units like meters and kilograms, you end up with totally weird irrational numbers. Stay simple and use the ms as basic unit.

I seriously don't want something intended to be run every 0.003 s being run every 0.002 s because of rounding.

**Comment by AndrewCarterUK** [comment]
I'm not sure the physics analogy is appropriate - both milliseconds and seconds are 'natural' units.

I also don't think there's any backwards compatibility issue. Event loop timers and sleep() calls (etc) are very approximate delays and advertised as such. An implementation being able to improve the accuracy of their timers wouldn't cause a BC break - and not any more than if you just switched it out for a different implementation that also had a different resolution.

edit: To clarify, if the method was to use a millisecond delay the documentation would specify that the delay is approximate and shouldn't be relied upon as accurate (it can't be).

**Comment by kelunik** [comment]
@trowski Just because it's an `int`, we won't change the unit in case of a future 0.1 ms accuracy.

Unit ≠ Type.

**Comment by AndrewCarterUK** [comment]
@kelunik - That's exactly what @trowski is getting at. Your approach sets a minimum resolution that cant be improved upon, using a float avoids this.

**Comment by kelunik** [comment]
@AndrewCarterUK Just to be clear, we have to answer two questions here:
- Seconds or milliseconds
- `int` or `float` (`float` of course if we choose seconds as unit of time)

**Comment by AndrewCarterUK** [comment]
@kelunik - Am aware :) It is still the case that using `int` rather than `float` (with either unit) sets a minimum resolution that cannot be improved upon without a backwards compatibility break.

**Comment by bwoebi** [comment]
@AndrewCarterUK I meant that we'll have simple integers, an unit which is simplest to operate on.

Sure, I get that point, and I'm still preferring to have integers … well few questions:
- What would you ever need µs resolution for?
- Will _all_ the backends support µs resolution?

Also, as we today need to cap to ms, it still is technically a BC break when we extend that to µs [we always can extend it to floats, even with PHP 7 strict types, we allow int->float widening].

**Comment by AndrewCarterUK** [comment]
@bwoebi - I've got no answer for needing microsecond resolution. The only thing I can add is that we have been surprised by changing tech capabilities in the past (Bill Gates's 640 kB of RAM comment) - but I'm not sure that's too applicable here.

Also, you wouldn't be able to change a type hint on an interface without breaking implementations and making a major version change. You're right that the code would work but there would be an error for the method signatures of the implementations not matching the interface.

**Comment by bwoebi** [comment]
yea, right, if we were to use PHP 7 and actually specify a type here ;-) But in reality it isn't a problem here.

With that though, if we change from millisecond to microsecond, there will be some reactors still being limited to millisecond and others to microsecond, which is a consistency break then. It's just not as apparent.

Forcing int here also makes this much more obvious that there actually is a millisecond resolution granularity.

[Ad. I'm sure, even if we had like a million clock cycles per nanosecond, our constraints are still limited to the speed of light (requests/jobs/... won't be served faster, only more massively), which is why milliseconds will probably be good enough until all eternity.]

**Comment by assertchris** [comment]
`$loop->delay(0.1, ...) // 0.10000000000001` <3

**Comment by rdlowrey** [comment]
I feel like milliseconds would probably make more sense here for a few reasons ...
- There is a very practical argument to make that PHP is not going to be fast enough in the near-term (or medium-term, for that matter) to make sub-millisecond loop iteration feasible.
- The major underlying compiled event loop libraries (kqueue, epoll, libevent and libuv) all use millisecond resolution; it makes sense to follow the lead of the primary implementations in this space and doing otherwise would probably be a violation of the law of least surprise.
- Due to modern operating system task-switching you generally can't work under the expectation that your process will get CPU time at intervals below a few milliseconds. Suggesting to API users that they can schedule things at sub-millisecond intervals only sets your library up for a torrent of bug reports (and general confusion) because it's a promise on which you literally cannot deliver. Roughly 10ms is the standard timer resolution for non-realtime operating systems.

[ntp.org](http://www.ntp.org/ntpfaq/NTP-s-sw-clocks-quality.htm) sums it up nicely:

> A high resolution does not help you anything if you can't read the clock. Therefore the smallest possible increase of time that can be experienced by a program is called precision.
- It's important to note also that just by nature of using millisecond units we are not foregoing the possibility of sub-millisecond resolution in the future. As long as we explicitly omit an `int` or `float` scalar type in the declaration we can easily support nanosecond resolution in the future. I was pleased to see that there was no explicit `int` requirement.
- The idea that we want to support nanosecond resolution at some point in the future is an argument _in favor_ of using milliseconds as the unit of measure because does anyone seriously want to express a nanosecond interval (1e-9) as 0.0000000001 ? Using milliseconds for now would at least make that more palatable. Expressing timer resolution in milliseconds allows us to get the maximum possible scheduling accuracy today (i.e. not using floating point math) while better supporting the potential future reality of nanosecond resolution.
- Floating point math is literally the worst

Anyhow ... those are my thoughts ... feel free to disagree. Hope everyone has a nice day :)

P.S. in the amp library we originally used one-second resolution and the floating point math quickly turned into a nightmare so take that for what it's worth.

**Comment by AndrewCarterUK** [comment]
It seems like there is enough consensus in this thread to warrant moving forward on this basis.

Again, if anyone wants to submit a PR - if not I'll do it next week.

**Comment by kelunik** [comment]
PR done.

**Comment by AndrewCarterUK** [comment]
Merged.

Closing this now but happy to reopen if anyone has anything else to add.
