### ISSUE TITLE
Waiting for exceptional conditions

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#19]
We already have methods for detecting when streams have readable or writeable data - but you can also poll for 'exceptional conditions' on a stream (I'm thinking `POLLPRI`).

In a `stream_select` call this is the `$except` parameter.

I'm currently doing some work on the Raspberry Pi which requires this for interrupt handling (this event is triggered when the voltage changes on a pin to simulate an interrupt). Though I know of no examples, I'd imagine this is a common technique for simulating interrupts in userland.

What are our thoughts? Are there any reasons not to add this?

**Comment by kelunik** [comment]
Do other drivers such as UV and EV support that?

**Comment by AndrewCarterUK** [comment]
Good question, doesn't appear that EV does: http://lists.schmorp.de/pipermail/libev/2015q3/002556.html

That pretty much closes this one - I'll reopen if anyone has anything to add.

**Comment by bwoebi** [comment]
In general you also just could have two separate streams, one for urgent interrupts, one for normal information.
Is there really something which isn't doable in any other way?

**Comment by AndrewCarterUK** [comment]
The sysfs GPIO driver triggers POLLPRI for interrupts. The normal read event will also be triggered but will not clear after having been read and rewinded.

**Comment by bwoebi** [comment]
These are things which then should be handled by individual loop drivers (e.g. a separate function inside the concrete driver). [This is btw. why I'd like to have functions instead of a static class - to add _specific_ features with separate functions … as it isn't possible to monkeypatch static classes.]

**Comment by AndrewCarterUK** [comment]
Its an example of why I think a static class is better. The GPIO library that I'm writing will be completely incompatible with this event loop standard. And that's okay. I shouldn't pretend that it is compliant and interoperable when it won't be. I will need to couple to a specific event loop implementation rather than the standard.

**Comment by bwoebi** [comment]
Well, that's what I'm saying. You then will still need an accessor to the concrete function of the class you're coupling your code to [to access the global instance of throw if method not present]. Hence you'll just add a function \MyLoop\foo() (which then also is consistent with \Loop\bar() (whatever our namespace is))

Instead of having once MyLoop\foo() and once Loop::bar() … different styles, not consistent.

**Comment by AndrewCarterUK** [comment]
Why would I want to use the global accessor from a standard that I can't use?

I'll need to couple to an event loop implementation that does support my requirements instead - one that is completely disconnected from our work here.

I've seen some really dangerous stuff in PSR-7 from people trying to extend it and make it fit their use case, the Slim framework is the best example. People think they're using PSR-7 but they're not, they're using something that is very similar, passes tests but fundamentally breaks when you try and use it for what the standard was actually designed for: interoperability.

**Comment by bwoebi** [comment]
Because a single functionality can't be provided by a certain concrete, that shouldn't mean that that functionality can't be interoperable. We e.g. might extend provide separate interfaces for separate functionality. (or someone will create a defacto standard with his own single-method interface.)

You shouldn't _extend_ the loop interface, but achieve the goals through the means of composition.

`class NativeWithPOLLPRI implements Loop, POLLPRI { /* ... */ }` … At that point, if you use something which requires `POLLPRI` interface (providing an `onPOLLPRI()` function), you need to choose between the implementations implementing it. But these implementations a) will still be compatible with our Loop interface and b) may still have themselves different backends.

And just because you can do bullshit, we shouldn't make the legitimate cases unnecessarily hard/impossible.

Just because I require an extension of it in my sysfs GPIO handling library, that still means that you'll be able to interoperate with that library, as long as the loop will implement a certain interface.

What you are proposing is defacto also hindering ourselves at providing standards accompanying the main loop interface.

**Comment by AndrewCarterUK** [comment]
With the '::get()' method on the loop calling code could just locate the driver that is in scope and test if it implemented the additional interface that they required.

They should almost certainly make calls that are not part of the standard to the driver directly, rather than relying on functions that may or may not be defined.
