### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#34]
Should we go with `Interop\Async` as namespace instead of `Interop\Async\EventLoop`?

[I created a promise draft](https://gist.github.com/kelunik/9bd92e23c4b734b457c610acf7393b98), using `Interop\Async\Promise\Promise` seems bad and as we just have a few interfaces, I think it'd be fine to use just `Interop\Async` as namespace for both.

**Comment by bwoebi** [comment]
I agree on that one, makes it easier to just import one namespace for all promisy and loopy stuff. (like promise transformation functions we'll probably provide (?))

also… less to type :-D

Interop\Async should provide its fundamental primitives at its main namespace - not need to split that up. (If we'd have naming conflicts, that'd be anyway bad as it makes importing harder/requires aliases - so that should be avoided anyway.)

**Comment by WyriHaximus** [comment]
> also… less to type :-D

IDE autocompletion :stuck_out_tongue:

**Comment by sagebind** [comment]
I'm in favor of a single, shorter namespace.

**Comment by kelunik** [comment]
Looks like we have consensus here. :+1:
