### ISSUE TITLE
Drop Loop::supports

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#50]
Should we drop `Loop::supports` and rely only on the thrown exception?

Usually, if you need signal handling, you will error out if you don't have it available anyway. If you need `if` ... `else` anyway, we can also use `try` ... `catch` directly.

**Comment by bwoebi** [comment]
Yep, for the rare instances where we need _optional_ signal handling, we can just as well use try/catch.
It's not like you'd set and disable try/catch all the time, that it would be a performance issue either. [Creating exceptions is expensive.]

And typically we just error out here, so that's fine then.

I think I'm in favor here, especially as it lets us drop a method and something we need an unique constant for…

**Comment by WyriHaximus** [comment]
Yup, I'm in favor of this. Adding a method you generally only check during start up clutters the interface imho. Plus throwing an exception is more expressive.

**Comment by kelunik** [comment]
> Plus throwing an exception is more expressive.

That's not an advantage. ^^

**Comment by WyriHaximus** [comment]
> > Plus throwing an exception is more expressive.
> 
> That's not an advantage. ^^

It is a personal preference :smile:

**Comment by kelunik** [comment]
Oops, read expensive.
