### ISSUE TITLE
Do we really need a common standard?

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#8]
Do we really need a common standard which then gets implemented multiple times? I think a common implementation makes much more sense. What do you think?

**Comment by assertchris** [comment]
Is there a reference to my statement; "Let's make it someone else's problem to implement a ^5 version..."?

**Comment by kelunik** [comment]
No, totally unrelated. I don't think there's value in multiple implementations anymore as there won't be any differences. If you have multiple implementations, you can't add anything to any implementation without breaking interoperability.

**Comment by bwoebi** [comment]
Actually, do we really need even a common implementation? It should be trivial to build adapters from one interface to the other currently. At least for the loop itself. [But I agree _if_ we do a common interface, we just should outright do a common implementation.]
What's more critical is what users are directly returned into their userspace - The Promise interface. Users will need to wrap each external Promise inside a Promise of their respective library. (yes, I know there's a repo … just saying.)
Not that it'd be too problematic; after all it's just a matter of a tiny function call when you want to have different Promise interfaces.

That said, I'm not opposed to a general implementation.

**Comment by kelunik** [comment]
Actually, a common event loop is more important than a common promise specification. There can be only one event loop at any time, but there could be multiple promises implementations at the same time in the same application.

As coroutines are entirely separate, Amp's current `coroutine` could even be built with support for multiple promises.

**Comment by bwoebi** [comment]
Also, note that we still first need the interface to actually base the several backends on it.

The implementation is … well, just an implementation detail after agreeing about the interface.

**Comment by kelunik** [comment]
Sure thing, but if we're going to provide the implementation as well, then it's not something that needs to be a PSR. Makes e.g. the decision to drop the `Interface` suffix easier. :-)

**Comment by bwoebi** [comment]
Dropping the `Interface` suffix is the best suggestion I've heard today :-)

**Comment by AndrewCarterUK** [comment]
There's lots of different ways to implement an event loop with performance differences. I know react have different implemetations using optional extensions. Implementations also require a much higher level of maintenance.

**Comment by bwoebi** [comment]
Sure, we have also different backends; but I think we should just aim to provide the fastest possible implementations for each possible backend (libev, libuv, libevent, native … that's all, right?).
If someone has a speed improvement, then he should just PR it here…?

I don't think that it would be more of a problem if we (maintainers of the current reactors) would instead maintain one single common implementation. I'd say it'd be less work for us all combined ;-)

**Comment by AndrewCarterUK** [comment]
That can also happen, but I don't see the two endeavors as mutually exclusive. Such an implementation would require an interface for testing too.

**Comment by AndrewCarterUK** [comment]
Testing\* and all the other reasons we program to interfaces. :)

**Comment by bwoebi** [comment]
Sure it requires tests … but only one single test suite for all the implementations.

As the test suite is tied to the interface, even if we don't provide an implementation, we still should provide a test suite as it will be generally applicable to every implementation.

**Comment by AndrewCarterUK** [comment]
My position on this is:
- A common implementation would require an interface anyway.
- Having that interface separate from the implementation (so that you can import only the interface) is a good idea and useful.
- If the major async libraries want to ditch their own loops and co-operate on an implementation for this interface that's great - but it's a separate decision and one that we should decouple from our work here as it comes with more baggage, politics, etc...

**Comment by WyriHaximus** [comment]
:+1:  @AndrewCarterUK's last comment

**Comment by sagebind** [comment]
I honestly don't have a particular example where this may be true, but it still may be the case that the tradeoffs are too great to have one implementation, since different implementations may be optimized for particular types of uses.

An important thing to consider: one day, I hope that PHP (PHP 8 maybe?) will move its I/O to async, or at least provide async I/O in  addition. If we provide a common interface now, people can start writing generic async packages for any implementation. If we can convince internals to implement the same interface if the engine ever provides an event loop, packages will automatically work with the native loop as well. Or that might be too much to hope for. :smile:

**Comment by AndrewCarterUK** [comment]
I'm closing this now, on the following basis:

Any implementation would, necessarily, have to be an implementation of a standard that we also created.  Therefore even if we did decide to go down that route (which I personally don't think we should), we would still need a standard and these should live in separate repositories.

If anyone has anything extra to add I will reopen :)
